### ISSUE TITLE
[feat] 라이브러리 개선 - 생명주기 메서드 구현

### ISSUE THREAD

**Issue by pereng11** [Group-Maker/Group_Maker#49]
# Abstract
리액트의 클래스형 컴포넌트를 참고하여 생명주기 메서드 구현

# Todos
- [x] didmount 메서드 구현
- [x] didUpdate 메서드 구현
- [x]  willUnmount 메서드 구현
